#!/bin/bash

if [[ $1 = "-h" ]]; then
  echo "clean can be specified as a parameter"
  exit
fi

$(
  cd ./UnderTest/build
  rm apk/UnderTest-test-unaligned.apk
  rm -r reports
  rm -r instrumentTest-results
)

if [[ $1 = clean ]]; then
  ./gradlew clean connectedInstrumentTest
else
  ./gradlew connectedInstrumentTest
fi
open ./UnderTest/build/reports/instrumentTests/connected/index.html
